asterisk:
  addons:
    version: null
  configure_options:
  - --with-ssl=ssl
  - --with-crypto
  - --enable-shared-sounds
  menuselect:
    apps:
    - app_voicemail
    - app_queue
    - app_confbridge
    - app_directory
    - app_dial
    - app_playback
    - app_record
    - app_echo
    - app_mixmonitor
    channels:
    - chan_pjsip
    - chan_iax2
    - chan_local
    - chan_bridge_media
    disable_modules: []
    disable_sounds: []
    drivers:
    - res_musiconhold
    - res_pjsip
    - res_pjsip_session
    - res_pjsip_outbound_registration
    - res_pjsip_registrar
    - res_rtp_asterisk
    - res_timing_timerfd
    - res_crypto
    enable_apps:
    - app_voicemail
    - app_directory
    - app_confbridge
    - app_queue
    - app_dial
    - app_playback
    - app_echo
    - app_record
    - app_mixmonitor
    - app_chanspy
    - app_page
    - app_meetme
    - app_macro
    - app_verbose
    - app_system
    - app_authenticate
    enable_channels:
    - chan_sip
    - chan_local
    - chan_bridge_media
    - chan_agent
    enable_resources:
    - res_musiconhold
    - res_agi
    - res_clioriginate
    - res_timing_timerfd
    - res_timing_pthread
    - res_crypto
    - res_http_websocket
    exclude:
    - chan_dahdi
    - chan_misdn
    - app_festival
    minimal: true
  opus_codec: null
  source:
    url_template: https://downloads.asterisk.org/pub/telephony/asterisk/releases/asterisk-{version}.tar.gz
base:
  distribution: jessie
  image: debian/eol:jessie
  os: debian
build:
  args:
    ASTERISK_VERSION: 11.25.3
    DEBIAN_FRONTEND: noninteractive
  script: build-asterisk.sh
docker:
  environment:
    ASTERISK_GID: '1000'
    ASTERISK_UID: '1000'
  expose_ports:
  - 5060/udp
  - 5060/tcp
  - 10000-20000/udp
  ports:
  - 5060:5060/tcp
  - 5060:5060/udp
  - 10000-10200:10000-10200/udp
  registry: docker.io
  repository: asterisk
  tags:
  - 11.25.3_debian-jessie
  - 11.25.3_debian-jessie-amd64
  volumes:
  - /etc/asterisk
  - /var/lib/asterisk
  - /var/log/asterisk
  - /var/spool/asterisk
features:
  hep: false
  pjsip: false
  recordings: true
  tls: true
  websockets: true
packages:
  build:
  - build-essential
  - autoconf
  - binutils-dev
  - ca-certificates
  - curl
  - file
  - libcurl4-openssl-dev
  - libedit-dev
  - libgsm1-dev
  - libicu-dev
  - libjansson-dev
  - libncurses-dev
  - libogg-dev
  - libpopt-dev
  - libpqxx-dev
  - libresample1-dev
  - libspandsp-dev
  - libspeex-dev
  - libspeexdsp-dev
  - libsqlite3-dev
  - libssl-dev
  - libtool
  - libvorbis-dev
  - libxml2-dev
  - libxslt1-dev
  - make
  - odbcinst
  - patch
  - pkg-config
  - portaudio19-dev
  - procps
  - python3-dev
  - unixodbc
  - unixodbc-dev
  - uuid
  - uuid-dev
  - xmlstarlet
  - libsrtp0-dev
  eol_setup:
  - echo "APT::Get::force-yes \"true\";" > /etc/apt/apt.conf.d/90-force-yes
  - echo "Acquire::Check-Valid-Until \"false\";" > /etc/apt/apt.conf.d/90-disable-validity-check
  - echo "deb [check-valid-until=no] http://archive.debian.org/debian/ jessie main
    contrib non-free" > /etc/apt/sources.list
  - echo "deb [check-valid-until=no] http://archive.debian.org/debian/ jessie-backports
    main contrib non-free" >> /etc/apt/sources.list
  - echo "deb [check-valid-until=no] http://archive.debian.org/debian-security/ jessie/updates
    main contrib non-free" >> /etc/apt/sources.list
  runtime:
  - binutils
  - curl
  - libedit2
  - libgsm1
  - libjansson4
  - libogg0
  - libpopt0
  - libresample1
  - libspandsp2
  - libspeex1
  - libspeexdsp1
  - libsqlite3-0
  - libvorbis0a
  - libxml2
  - libxslt1.1
  - odbcinst
  - portaudio19-dev
  - procps
  - python3
  - unixodbc
  - uuid
  - libcurl3
  - libssl1.0.0
  - libsrtp0
  - libncurses5
  - libpqxx-4.0
  - libicu52
version: 11.25.3
