"""
Golden regeneration tests for the template/Dockerfile generators.

These tests are the content-level safety net that the repo's own #1 rule
("NEVER edit files in `asterisk/` - they are auto-generated") relies on:
they regenerate a representative version set into a throwaway git worktree
and fail if any regenerated byte differs from the tracked golden file.
This catches both generator regressions and hand-edits to generated files
in seconds, instead of waiting for a 30-60 minute Docker build in CI.

See main/plans/001-golden-regeneration-tests.md for the full design.

Two tiers, expressed in a single per-version assertion:
  - Tier 1 (always runs, hermetic): configs/generated/*.yml, build.sh,
    healthcheck.sh, entrypoint.sh - none of these pass through dockerfmt.
  - Tier 2 (requires docker): the Dockerfile, which is piped through
    `docker run ghcr.io/reteps/dockerfmt`. When docker is unavailable the
    generator silently skips formatting (lib/dockerfile_generator.py:164-166)
    and Dockerfile bytes would not match the tracked (formatted) goldens,
    so Dockerfiles are excluded from the comparison on docker-less hosts.
    ubuntu-latest CI runners always have docker, so the tier always runs there.
"""

import os
import shutil
import subprocess
import pytest

# Repo root is one level up from tests/ (the tests run from a checkout of
# the project, so __file__ resolves under <repo>/tests/).
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# One version per distinct generator code path - see the plan's
# "Representative version set" table. The `git` version is deliberately
# excluded: its config embeds a live HEAD SHA fetched via `git ls-remote`
# (build-asterisk.sh:234,519), so it is not hermetic.
VERSIONS = [
    "22.10.1",     # modern variant, arm64+amd64, semantic tags
    "23.4.1",      # runtime_autoderive, member-level experimental tag (trixie + forky)
    "20.7-cert11", # certified URL template + cert version parsing
    "19.8.1",      # bookworm distribution layer
    "11.25.3",     # asterisk-11 variant
    "10.12.4",     # legacy variant
    "1.4.44",      # legacy-addons variant + addons tarball path
]

# Paths regenerated by `build-asterisk.sh --force-config --dry-run`.
# Scoped so the diff never picks up unrelated noise (e.g. the non-hermetic
# configs/generated/asterisk-git-master-*.yml, which drift because their
# git_sha is fetched live and is intentionally not covered here).
GENERATED_PATHSPECS = ["configs/generated/", "asterisk/"]

# Dockerfile tier is gated on docker being available; without it the
# generator silently skips dockerfmt (lib/dockerfile_generator.py:164-166)
# and Dockerfile bytes would not match the tracked (formatted) goldens.
HAVE_DOCKER = shutil.which("docker") is not None


@pytest.fixture(scope="session")
def worktree(tmp_path_factory):
    """A throwaway git worktree of HEAD.

    Regeneration is run inside the worktree (not the developer's working
    tree) so the diff is purely "regeneration vs tracked HEAD" with no
    contamination from local edits. `git worktree add` works from a repo
    that is itself a worktree (this checkout), and the worktree is always
    removed in teardown, even on test failure.
    """
    wt = tmp_path_factory.mktemp("golden") / "wt"
    subprocess.run(
        ["git", "worktree", "add", "--detach", str(wt)],
        check=True, cwd=REPO_ROOT, capture_output=True, text=True,
    )
    yield wt
    subprocess.run(
        ["git", "worktree", "remove", "--force", str(wt)],
        cwd=REPO_ROOT, capture_output=True, text=True,
    )


def _diff_args(paths_extras):
    """Build a git status/diff pathspec list (generated paths + extras)."""
    return ["--"] + GENERATED_PATHSPECS + paths_extras


@pytest.mark.parametrize("version", VERSIONS)
def test_regeneration_matches_tracked_output(worktree, version):
    """Regenerating <version> in a clean worktree leaves tracked files unchanged.

    Catches:
      - generator regressions (template/generator change without regen), and
      - hand-edits to generated files that diverge from what the generator emits.

    When docker is available the assertion covers every regenerated artifact
    (tier 1 + tier 2). When docker is unavailable the Dockerfile tier is
    excluded from the comparison, since the generator would emit unformatted
    Dockerfiles that intentionally do not match the tracked (formatted)
    goldens - but every hermetic artifact is still asserted byte-identical.
    """
    exclude_dockerfiles = not HAVE_DOCKER
    extra = [":!asterisk/*/Dockerfile"] if exclude_dockerfiles else []

    regen = subprocess.run(
        ["./scripts/build-asterisk.sh", version,
         "--force-config", "--dry-run"],
        cwd=worktree, capture_output=True, text=True,
    )
    assert regen.returncode == 0, (
        f"{version}: regeneration failed (rc={regen.returncode})\n"
        f"stdout:\n{regen.stdout[-2000:]}\n"
        f"stderr:\n{regen.stderr[-2000:]}"
    )

    status = subprocess.run(
        ["git", "status", "--porcelain"] + _diff_args(extra),
        cwd=worktree, capture_output=True, text=True, check=True,
    ).stdout
    assert status == "", (
        f"{version}: regeneration differs from tracked files"
        + (" (Dockerfile tier excluded - docker unavailable)\n" if exclude_dockerfiles
           else "\n")
        + subprocess.run(
            ["git", "diff"] + _diff_args(extra),
            cwd=worktree, capture_output=True, text=True, check=True,
        ).stdout[:4000]
    )
