volumes:
  asterisk_logs:

services:
  # Asterisk PBX
  asterisk:
    build:
      context: ./asterisk
      dockerfile: Dockerfile
    ports:
      - "5060:5060/udp" # SIP UDP
      - "5060:5060/tcp" # SIP TCP
      - "10000-10199:10000-10199/udp" # RTP Media (ensure these ports are open in firewall)
    volumes:
      - asterisk_logs:/var/log/asterisk
      - ./asterisk/keys:/etc/asterisk/keys:ro
    env_file: .env
    restart: unless-stopped
